"""
Domain models and spatial graph definitions for the SafePlay crowd safety orchestrator.

This module defines the validation schemas for telemetry data and safety scripts, 
as well as the directed spatial graph representations used for stadium venue modeling 
and alternative egress routing calculation.
"""

import logging
from typing import Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict, field_validator

# Configure module-level logger for logging warning/error messages
logger = logging.getLogger(__name__)

# Attempt to load Cython-accelerated routing function for high-frequency matrix operations.
# Falls back gracefully to pure Python implementations if the compiled .so/.pyd file is missing.
try:
    from src.routing import get_alternative_route_cy, find_optimal_path_cy
    HAS_CYTHON = True
except ImportError:
    HAS_CYTHON = False

# ---------------------------------------------------------------------------
# TelemetryPayload Definition
# ---------------------------------------------------------------------------
class TelemetryPayload(BaseModel):
    """
    Pydantic schema representing high-frequency crowd density and flow metrics 
    received from edge monitoring devices (e.g., camera sensors, smart turnstiles).
    
    Attributes:
        zone_id: Unique string identifying the physical quadrant or vomitory.
        crowd_density: Number of people per square meter in the zone.
        flow_rate_in: Rate of people entering the zone per minute.
        flow_rate_out: Rate of people exiting the zone per minute.
        timestamp: Unix epoch timestamp representing when telemetry was captured.
    """
    model_config = ConfigDict(extra="forbid")
    
    zone_id: str = Field(
        ..., 
        min_length=1, 
        max_length=64, 
        description="Unique identifier of the physical stadium quadrant/vomitory"
    )
    crowd_density: float = Field(
        ..., 
        ge=0.0, 
        le=20.0, 
        description="Estimated crowd density in people/m^2. Capped at 20.0 to prevent outlier ingestion."
    )
    flow_rate_in: float = Field(
        ..., 
        ge=0.0, 
        description="Rate of people entering the zone per minute"
    )
    flow_rate_out: float = Field(
        ..., 
        ge=0.0, 
        description="Rate of people exiting the zone per minute"
    )
    timestamp: float = Field(
        ..., 
        gt=0.0, 
        description="Epoch timestamp of telemetry collection"
    )
    signature: Optional[str] = Field(
        None,
        description="Optional HMAC SHA-256 signature of the telemetry payload"
    )


# ---------------------------------------------------------------------------
# InterventionScript Definition
# ---------------------------------------------------------------------------
# Pre-defined valid hazard levels, gate control actions, and transit actions to enforce at runtime.
_VALID_HAZARD_LEVELS = {"low", "medium", "high", "critical"}
_VALID_GATE_ACTIONS = {"KEEP_OPEN", "SLOW_ENTRY", "CLOSE_IMMEDIATELY", "REVERSE_FLOW"}
_VALID_TRANSIT_ACTIONS = {"KEEP_NOMINAL", "INCREASE_SHUTTLE_FREQUENCY", "REDIRECT_METRO_PASSENGER_ENTRY", "HOLD_METRO_TRAINS"}

class InterventionScript(BaseModel):
    """
    Pydantic schema representing safety intervention scripts generated by 
    the Small Language Model (SLM) or static fallback rules for FIFA World Cup 2026.
    
    Attributes:
        zone_id: The physical zone ID this script applies to.
        hazard_level: Assessed level ('low', 'medium', 'high', or 'critical').
        action_required: Boolean flag indicating if operator confirmation is required.
        reroute_target: Optional zone ID to redirect traffic towards.
        signage_instruction_en: English text to display on dynamic digital signage.
        signage_instruction_es: Spanish text to display on dynamic digital signage.
        signage_instruction_fr: French text to display on dynamic digital signage.
        audio_announcement_en: English PA audio announcement transcript.
        audio_announcement_es: Spanish PA audio announcement transcript.
        audio_announcement_fr: French PA audio announcement transcript.
        gate_action: Turnstile actuation action ('KEEP_OPEN', 'SLOW_ENTRY', etc.).
        accessibility_route_target: Optional alternative zone ID for disabled/ADA visitors.
        accessibility_instruction: Optional specialized routing guidelines for ADA visitors.
        transit_dispatch_action: Subway/shuttle dispatch control action.
        transit_instruction: Public transit guidelines for coordinators and volunteers.
        rationale: Brief natural language explanation for the recommendation.
    """
    model_config = ConfigDict(extra="forbid")
    
    zone_id: str = Field(
        ..., 
        min_length=1, 
        max_length=64, 
        description="The physical stadium quadrant/vomitory identifier"
    )
    hazard_level: str = Field(
        ..., 
        description="Assessed hazard level: 'low', 'medium', 'high', 'critical'"
    )
    action_required: bool = Field(
        ..., 
        description="True if operator must approve signage or gate changes"
    )
    reroute_target: Optional[str] = Field(
        None, 
        description="Alternative zone_id to redirect crowd flow if action_required is True"
    )
    signage_instruction_en: str = Field(
        ..., 
        max_length=120, 
        description="English signage message (maximum 120 characters)"
    )
    signage_instruction_es: str = Field(
        ..., 
        max_length=120, 
        description="Spanish signage message translation (maximum 120 characters)"
    )
    signage_instruction_fr: str = Field(
        ..., 
        max_length=120, 
        description="French signage message translation (maximum 120 characters)"
    )
    audio_announcement_en: str = Field(
        ..., 
        max_length=200, 
        description="English PA audio transcript (maximum 200 characters)"
    )
    audio_announcement_es: str = Field(
        ..., 
        max_length=200, 
        description="Spanish PA audio transcript translation (maximum 200 characters)"
    )
    audio_announcement_fr: str = Field(
        ..., 
        max_length=200, 
        description="French PA audio transcript translation (maximum 200 characters)"
    )
    gate_action: str = Field(
        ..., 
        description="Turnstile/gate control action: 'KEEP_OPEN', 'SLOW_ENTRY', 'CLOSE_IMMEDIATELY', 'REVERSE_FLOW'"
    )
    accessibility_route_target: Optional[str] = Field(
        None, 
        description="Alternative ADA accessible route target"
    )
    accessibility_instruction: Optional[str] = Field(
        None, 
        description="Special ADA direction and guidance"
    )
    transit_dispatch_action: str = Field(
        ..., 
        description="Transit coordination command"
    )
    transit_instruction: str = Field(
        ..., 
        description="Transit coordination guidance message"
    )
    rationale: str = Field(
        ..., 
        max_length=120, 
        description="Zero-fluff explanation of the assessment (maximum 10 words)"
    )

    @field_validator("hazard_level")
    @classmethod
    def validate_hazard_level(cls, v: str) -> str:
        """Enforces that the hazard level matches one of the pre-approved severity tokens."""
        if v not in _VALID_HAZARD_LEVELS:
            raise ValueError(f"hazard_level must be one of {_VALID_HAZARD_LEVELS}")
        return v

    @field_validator("gate_action")
    @classmethod
    def validate_gate_action(cls, v: str) -> str:
        """Enforces that the gate action matches one of the pre-approved turnstile command states."""
        if v not in _VALID_GATE_ACTIONS:
            raise ValueError(f"gate_action must be one of {_VALID_GATE_ACTIONS}")
        return v

    @field_validator("transit_dispatch_action")
    @classmethod
    def validate_transit_dispatch_action(cls, v: str) -> str:
        """Enforces that the transit dispatch action matches one of the pre-approved transit command states."""
        if v not in _VALID_TRANSIT_ACTIONS:
            raise ValueError(f"transit_dispatch_action must be one of {_VALID_TRANSIT_ACTIONS}")
        return v


# ---------------------------------------------------------------------------
# Spatial Graph Classes
# ---------------------------------------------------------------------------
class SpatialNode(BaseModel):
    """
    Represents a node within the physical directed spatial graph.
    
    Attributes:
        zone_id: The unique identifier for this physical zone.
        capacity: Maximum safe density threshold (people/m^2).
        current_density: Current estimated density, updated continuously.
    """
    zone_id: str
    capacity: float  # Max safe capacity
    current_density: float = 0.0


class SpatialEdge(BaseModel):
    """
    Represents a directed egress route/corridor between two physical nodes.
    
    Attributes:
        source: Starting zone identifier.
        target: Destination zone identifier.
        max_flow_rate: Maximum capacity throughput in people/minute.
        current_flow_rate: Current rate of crowd flow, updated from telemetry.
    """
    source: str
    target: str
    max_flow_rate: float  # Max throughput in people/minute
    current_flow_rate: float = 0.0


class SpatialGraph:
    """
    Represents physical stadium corridors as a directed spatial graph matrix G = (V, E).
    Used to dynamically calculate alternative routing paths during zone overcrowding.
    """
    def __init__(self, nodes: List[SpatialNode], edges: List[SpatialEdge]):
        """
        Initializes the spatial graph with vertices (nodes) and edges.
        
        Args:
            nodes: List of SpatialNode objects representing venue zones.
            edges: List of SpatialEdge objects representing transit routes between zones.
        """
        # Node lookup map for O(1) query access
        self.nodes: Dict[str, SpatialNode] = {n.zone_id: n for n in nodes}
        
        # Adjacency matrix: maps source zone to a dictionary of target edges
        self.adjacency: Dict[str, Dict[str, SpatialEdge]] = {n.zone_id: {} for n in nodes}
        for edge in edges:
            if edge.source in self.adjacency and edge.target in self.adjacency:
                self.adjacency[edge.source][edge.target] = edge

    @staticmethod
    def get_default_world_cup_graph() -> "SpatialGraph":
        """
        Factory method to generate the default spatial graph representing FIFA 2026 stadium corridors.
        """
        return SpatialGraph(
            nodes=[
                SpatialNode(zone_id="Gate_A", capacity=2.5),
                SpatialNode(zone_id="Gate_B", capacity=2.5),
                SpatialNode(zone_id="Gate_C", capacity=2.0),
                SpatialNode(zone_id="Corridor_1", capacity=4.0),
                SpatialNode(zone_id="Corridor_2", capacity=4.0),
                SpatialNode(zone_id="Main_Concourse", capacity=5.0),
                SpatialNode(zone_id="Transit_Hub", capacity=6.0),
                SpatialNode(zone_id="Transit_Shuttle", capacity=5.0)
            ],
            edges=[
                SpatialEdge(source="Gate_A", target="Corridor_1", max_flow_rate=120.0),
                SpatialEdge(source="Gate_B", target="Corridor_2", max_flow_rate=120.0),
                SpatialEdge(source="Gate_C", target="Main_Concourse", max_flow_rate=80.0),
                SpatialEdge(source="Corridor_1", target="Main_Concourse", max_flow_rate=200.0),
                SpatialEdge(source="Corridor_2", target="Main_Concourse", max_flow_rate=200.0),
                SpatialEdge(source="Main_Concourse", target="Transit_Hub", max_flow_rate=300.0),
                SpatialEdge(source="Main_Concourse", target="Transit_Shuttle", max_flow_rate=250.0)
            ]
        )

    def update_node_density(self, zone_id: str, density: float) -> None:
        """
        Updates the current crowd density of a specific node.
        
        Args:
            zone_id: Node key identifier.
            density: The new measured density value.
        """
        if zone_id in self.nodes:
            self.nodes[zone_id].current_density = density

    def update_edge_flow(self, source: str, target: str, flow_rate: float) -> None:
        """
        Updates the current flow rate along a directed route between two nodes.
        
        Args:
            source: Source zone identifier.
            target: Target zone identifier.
            flow_rate: The updated flow rate in people/minute.
        """
        if source in self.adjacency and target in self.adjacency[source]:
            self.adjacency[source][target].current_flow_rate = flow_rate

    def get_alternative_route(self, overloaded_zone: str) -> Optional[str]:
        """
        Finds adjacent zones with density below capacity limits to reroute flow.
        Prefers the Cython-optimised path; falls back to pure Python on error.
        
        Args:
            overloaded_zone: The key identifier of the currently crowded zone.
            
        Returns:
            The zone ID of the adjacent neighbor with the most spare capacity,
            or None if no neighbor has available capacity.
        """
        # 1. Attempt to run Cython-optimized routing routine if loaded
        if HAS_CYTHON:
            try:
                return get_alternative_route_cy(self.nodes, self.adjacency, overloaded_zone)
            except Exception as exc:
                logger.warning("Cython route lookup failed, falling back to pure Python: %s", exc)

        # 2. Pure Python fallback routing logic
        if overloaded_zone not in self.adjacency:
            return None
        
        # Find all outgoing routes from the overloaded zone
        candidates = []
        for target, edge in self.adjacency[overloaded_zone].items():
            target_node = self.nodes.get(target)
            # Filter adjacent nodes that have spare capacity (current_density < capacity)
            if target_node and target_node.current_density < target_node.capacity:
                spare_capacity = target_node.capacity - target_node.current_density
                candidates.append((target, spare_capacity))
        
        # Select the candidate node with the maximum spare capacity in O(N) time complexity
        if candidates:
            return max(candidates, key=lambda x: x[1])[0]
            
        return None

    def find_optimal_egress_path(self, source_zone: str, target_zones: List[str]) -> Optional[List[str]]:
        """
        Calculates a multi-hop egress route from a source zone to a set of target exit zones.
        Prefers the compiled Cython-accelerated algorithm, falling back to a pure Python BFS.
        
        Args:
            source_zone: The key identifier of the starting node.
            target_zones: A list of candidate destination exit zone IDs.
            
        Returns:
            A list of zone IDs representing the path, or None if no path with spare capacity exists.
        """
        if HAS_CYTHON:
            try:
                return find_optimal_path_cy(self.nodes, self.adjacency, source_zone, target_zones)
            except Exception as exc:
                logger.warning("Cython optimal path search failed: %s", exc)
                
        # Pure Python fallback
        if source_zone is None or target_zones is None:
            return None
        if source_zone in target_zones:
            return [source_zone]
            
        queue = [[source_zone]]
        visited = {source_zone}
        while queue:
            path = queue.pop(0)
            current_zone = path[len(path) - 1]
            if current_zone in target_zones:
                return path
            if current_zone in self.adjacency:
                for neighbor in self.adjacency[current_zone]:
                    if neighbor not in visited:
                        node_obj = self.nodes.get(neighbor)
                        if node_obj and node_obj.current_density < node_obj.capacity:
                            visited.add(neighbor)
                            new_path = list(path)
                            new_path.append(neighbor)
                            queue.append(new_path)
        return None


# ---------------------------------------------------------------------------
# Copilot API Schemas
# ---------------------------------------------------------------------------
class CopilotRequest(BaseModel):
    """
    Pydantic schema representing a user query to the GenAI Stadium Operations Copilot.
    """
    prompt: str = Field(
        ..., 
        min_length=1,
        description="The natural language query or command from the venue operator"
    )
    zone_id: Optional[str] = Field(
        None, 
        description="Optional target zone ID to focus query context on"
    )


class CopilotResponse(BaseModel):
    """
    Pydantic schema representing the structured response returned by the GenAI Copilot.
    """
    answer: str = Field(
        ..., 
        description="The natural language response or instruction generated by the Copilot"
    )
    timestamp: float = Field(
        ..., 
        description="Unix epoch timestamp of the response generation"
    )
    active_incident_count: int = Field(
        ..., 
        description="Total number of zones currently with elevated hazard level or action required"
    )
    hazard_summary: str = Field(
        ..., 
        description="Short, high-level summary of the overall stadium hazard status"
    )
