"""
Domain models and spatial graph definitions for the SafePlay crowd safety orchestrator.

This module defines the validation schemas for telemetry data and safety scripts, 
as well as the directed spatial graph representations used for stadium venue modeling 
and alternative egress routing calculation.
"""

import logging
from typing import Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict, field_validator

# Configure module-level logger for logging warning/error messages
logger = logging.getLogger(__name__)

# Attempt to load Cython-accelerated routing function for high-frequency matrix operations.
# Falls back gracefully to pure Python implementations if the compiled .so/.pyd file is missing.
try:
    from src.routing import get_alternative_route_cy
    HAS_CYTHON = True
except ImportError:
    HAS_CYTHON = False

# ---------------------------------------------------------------------------
# TelemetryPayload Definition
# ---------------------------------------------------------------------------
class TelemetryPayload(BaseModel):
    """
    Pydantic schema representing high-frequency crowd density and flow metrics 
    received from edge monitoring devices (e.g., camera sensors, smart turnstiles).
    
    Attributes:
        zone_id: Unique string identifying the physical quadrant or vomitory.
        crowd_density: Number of people per square meter in the zone.
        flow_rate_in: Rate of people entering the zone per minute.
        flow_rate_out: Rate of people exiting the zone per minute.
        timestamp: Unix epoch timestamp representing when telemetry was captured.
    """
    model_config = ConfigDict(extra="forbid")
    
    zone_id: str = Field(
        ..., 
        min_length=1, 
        max_length=64, 
        description="Unique identifier of the physical stadium quadrant/vomitory"
    )
    crowd_density: float = Field(
        ..., 
        ge=0.0, 
        le=20.0, 
        description="Estimated crowd density in people/m^2. Capped at 20.0 to prevent outlier ingestion."
    )
    flow_rate_in: float = Field(
        ..., 
        ge=0.0, 
        description="Rate of people entering the zone per minute"
    )
    flow_rate_out: float = Field(
        ..., 
        ge=0.0, 
        description="Rate of people exiting the zone per minute"
    )
    timestamp: float = Field(
        ..., 
        gt=0.0, 
        description="Epoch timestamp of telemetry collection"
    )


# ---------------------------------------------------------------------------
# InterventionScript Definition
# ---------------------------------------------------------------------------
# Pre-defined valid hazard levels and gate control actions to enforce at runtime.
_VALID_HAZARD_LEVELS = {"low", "medium", "high", "critical"}
_VALID_GATE_ACTIONS = {"KEEP_OPEN", "SLOW_ENTRY", "CLOSE_IMMEDIATELY", "REVERSE_FLOW"}

class InterventionScript(BaseModel):
    """
    Pydantic schema representing safety intervention scripts generated by 
    the Small Language Model (SLM) or static fallback rules.
    
    Attributes:
        zone_id: The physical zone ID this script applies to.
        hazard_level: Assessed level ('low', 'medium', 'high', or 'critical').
        action_required: Boolean flag indicating if operator confirmation is required.
        reroute_target: Optional zone ID to redirect traffic towards.
        signage_instruction: Messaging instruction for digital status displays.
        gate_action: Turnstile actuation action ('KEEP_OPEN', 'SLOW_ENTRY', etc.).
        rationale: Brief natural language explanation for the recommendation.
    """
    model_config = ConfigDict(extra="forbid")
    
    zone_id: str = Field(
        ..., 
        min_length=1, 
        max_length=64, 
        description="The physical stadium quadrant/vomitory identifier"
    )
    hazard_level: str = Field(
        ..., 
        description="Assessed hazard level: 'low', 'medium', 'high', 'critical'"
    )
    action_required: bool = Field(
        ..., 
        description="True if operator must approve signage or gate changes"
    )
    reroute_target: Optional[str] = Field(
        None, 
        description="Alternative zone_id to redirect crowd flow if action_required is True"
    )
    signage_instruction: str = Field(
        ..., 
        max_length=120, 
        description="Short text to display on dynamic digital signage (maximum 120 characters)"
    )
    gate_action: str = Field(
        ..., 
        description="Turnstile/gate control action: 'KEEP_OPEN', 'SLOW_ENTRY', 'CLOSE_IMMEDIATELY', 'REVERSE_FLOW'"
    )
    rationale: str = Field(
        ..., 
        max_length=100, 
        description="Zero-fluff explanation of the assessment (maximum 10 words)"
    )

    @field_validator("hazard_level")
    @classmethod
    def validate_hazard_level(cls, v: str) -> str:
        """Enforces that the hazard level matches one of the pre-approved severity tokens."""
        if v not in _VALID_HAZARD_LEVELS:
            raise ValueError(f"hazard_level must be one of {_VALID_HAZARD_LEVELS}")
        return v

    @field_validator("gate_action")
    @classmethod
    def validate_gate_action(cls, v: str) -> str:
        """Enforces that the gate action matches one of the pre-approved turnstile command states."""
        if v not in _VALID_GATE_ACTIONS:
            raise ValueError(f"gate_action must be one of {_VALID_GATE_ACTIONS}")
        return v


# ---------------------------------------------------------------------------
# Spatial Graph Classes
# ---------------------------------------------------------------------------
class SpatialNode(BaseModel):
    """
    Represents a node within the physical directed spatial graph.
    
    Attributes:
        zone_id: The unique identifier for this physical zone.
        capacity: Maximum safe density threshold (people/m^2).
        current_density: Current estimated density, updated continuously.
    """
    zone_id: str
    capacity: float  # Max safe capacity
    current_density: float = 0.0


class SpatialEdge(BaseModel):
    """
    Represents a directed egress route/corridor between two physical nodes.
    
    Attributes:
        source: Starting zone identifier.
        target: Destination zone identifier.
        max_flow_rate: Maximum capacity throughput in people/minute.
        current_flow_rate: Current rate of crowd flow, updated from telemetry.
    """
    source: str
    target: str
    max_flow_rate: float  # Max throughput in people/minute
    current_flow_rate: float = 0.0


class SpatialGraph:
    """
    Represents physical stadium corridors as a directed spatial graph matrix G = (V, E).
    Used to dynamically calculate alternative routing paths during zone overcrowding.
    """
    def __init__(self, nodes: List[SpatialNode], edges: List[SpatialEdge]):
        """
        Initializes the spatial graph with vertices (nodes) and edges.
        
        Args:
            nodes: List of SpatialNode objects representing venue zones.
            edges: List of SpatialEdge objects representing transit routes between zones.
        """
        # Node lookup map for O(1) query access
        self.nodes: Dict[str, SpatialNode] = {n.zone_id: n for n in nodes}
        
        # Adjacency matrix: maps source zone to a dictionary of target edges
        self.adjacency: Dict[str, Dict[str, SpatialEdge]] = {n.zone_id: {} for n in nodes}
        for edge in edges:
            if edge.source in self.adjacency and edge.target in self.adjacency:
                self.adjacency[edge.source][edge.target] = edge

    def update_node_density(self, zone_id: str, density: float) -> None:
        """
        Updates the current crowd density of a specific node.
        
        Args:
            zone_id: Node key identifier.
            density: The new measured density value.
        """
        if zone_id in self.nodes:
            self.nodes[zone_id].current_density = density

    def update_edge_flow(self, source: str, target: str, flow_rate: float) -> None:
        """
        Updates the current flow rate along a directed route between two nodes.
        
        Args:
            source: Source zone identifier.
            target: Target zone identifier.
            flow_rate: The updated flow rate in people/minute.
        """
        if source in self.adjacency and target in self.adjacency[source]:
            self.adjacency[source][target].current_flow_rate = flow_rate

    def get_alternative_route(self, overloaded_zone: str) -> Optional[str]:
        """
        Finds adjacent zones with density below capacity limits to reroute flow.
        Prefers the Cython-optimised path; falls back to pure Python on error.
        
        Args:
            overloaded_zone: The key identifier of the currently crowded zone.
            
        Returns:
            The zone ID of the adjacent neighbor with the most spare capacity,
            or None if no neighbor has available capacity.
        """
        # 1. Attempt to run Cython-optimized routing routine if loaded
        if HAS_CYTHON:
            try:
                return get_alternative_route_cy(self.nodes, self.adjacency, overloaded_zone)
            except Exception as exc:
                logger.warning("Cython route lookup failed, falling back to pure Python: %s", exc)

        # 2. Pure Python fallback routing logic
        if overloaded_zone not in self.adjacency:
            return None
        
        # Find all outgoing routes from the overloaded zone
        candidates = []
        for target, edge in self.adjacency[overloaded_zone].items():
            target_node = self.nodes.get(target)
            # Filter adjacent nodes that have spare capacity (current_density < capacity)
            if target_node and target_node.current_density < target_node.capacity:
                spare_capacity = target_node.capacity - target_node.current_density
                candidates.append((target, spare_capacity))
        
        # Select the candidate node with the maximum spare capacity in O(N) time complexity
        if candidates:
            return max(candidates, key=lambda x: x[1])[0]
            
        return None
